### ISSUE TITLE
How to register the alias? please...

### ISSUE THREAD

**Issue by resnef** [dmitry-ivanov/laravel-dark-sky#1]

**Comment by dmitry-ivanov** [comment]
Probably you're talking about Laravel Facade aliases?

Then, please take a look here:
https://github.com/dmitry-ivanov/dark-sky-api#laravel-support

If you're using Laravel 5.5+, then the service provider and facade alias would be registered [automatically for you](https://github.com/dmitry-ivanov/dark-sky-api/blob/master/composer.json#L42-L51).

If you're using Laravel < 5.5., then you have to register service provider and alias (optionally) manually:
https://laravel.com/docs/5.4/providers#registering-providers

For aliases, check `aliases` array in the same `config/app.php` file.
