### ISSUE TITLE
Installation stand alone

### ISSUE THREAD

**Issue by ptscopedev** [dmitry-ivanov/laravel-dark-sky#2]
Hi,

Sorry, I am not familiar with namespaces, normally use includes, but it does not matter what I do, I cannot get your class to work with our api key, can you help?

I want stand alone, could you suggest the correct folder structure to store, and how to call it?

Really really appreciated as your class looks the best type.

Regards

Rob

**Comment by dmitry-ivanov** [comment]
Hi!

Could you please provide the code you're trying to use and the error output?

PS: Are you using composer to include the package?
