### ISSUE TITLE
Use a formatter on the forecastUrl() function for the round() lat/lng.

### ISSUE THREAD

**Issue by veve40** [dmitry-ivanov/laravel-dark-sky#3]
### Versions:

- Package Version: ^1.1
- PHP Version: 7.3.6

### Description:
Hey!  :) 
I got a problem using the library, my **PHP locale** information was set to `fr_FR`, and it's making the `round()` function replace the _lat_ and _lng_ **dots** with **commas**. That leads to broke the featured request with a **400 Poorly formatted request** : 

https://api.darksky.net/forecast/[KEY]/45,509,-73,588

Using the [number_format function](https://www.php.net/manual/en/function.number-format.php) can fix this problem.

```
$latitude = number_format(round($parameters->getLatitude(), 3), 3);
$longitude = number_format(round($parameters->getLongitude(), 3), 3);
```

This is located in `src/Http/Request/UrlGenerator.php`.

### Steps to reproduce:

`setlocale(LC_NUMERIC, 'fr_FR');` before execute the `forecast` function.

**Comment by dmitry-ivanov** [comment]
Hey! 🙂 

Thank you for great description!

Fixed in release `1.1.1` 👍
